Initial Project Setup
Vylpes/Sonar pull request #1
Opened 2021-04-15 14:12 UTC by Vylpes

- Installs the initial node packages
- Setups the project layout
- Adds alerts
- Adds initial base string

2021-04-15 14:16 UTC, Vylpes commented on sonar.js
> +    console.log('app listening on port 3000');
Might change this rule

2021-04-15 14:16 UTC, Vylpes commented on sonar.js
> +app.use(express.static(path.join(__dirname, 'public')));
Need to add to the config

2021-04-15 14:16 UTC, Vylpes commented
- [ ] Add unit tests

2021-04-15 14:52 UTC, VylpesTester requested changes

2021-04-15 14:52 UTC, VylpesTester commented on helpers/alerts.js
> +exports.info = (str, message) => {
Would it be better to make the alerts a class? Such as:
- Create the class, which fetches the base string
- Have the alerts as methods under the class
- When being fetched for the pug you have another method which gets the final string

2021-04-15 14:52 UTC, VylpesTester commented on .gitignore
> +!/public/dist
Add an ignore for .DS_Store

2021-04-29 08:53 UTC, Vylpes commented
- [ ] Convert to TypeScript
- [ ] Setup TSLint
- [ ] Setup GitHub actions

2021-05-06 11:18 UTC, VylpesTester approved these changes

2021-05-06 11:18 UTC, merged